# Generated by Django 5.2.6 on 2025-09-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_deposit_transactions', to='finance.deposit'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('add_to_wallet', 'Add to Wallet'), ('remove_from_wallet', 'Remove from Wallet'), ('account_to_wallet', 'Account to Wallet'), ('wallet_to_account', 'Wallet to Account'), ('wallet_to_wallet', 'Wallet to Wallet'), ('account_to_account', 'Account to Account'), ('wallet_to_deposit_initial', 'Wallet to Deposit (Initial)'), ('profit_account', 'Account Profit Accrual'), ('profit_deposit_wallet', 'Deposit Profit to Wallet')], max_length=40),
        ),
    ]
