# Generated by Django 5.2.6 on 2025-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
