# Generated by Django 5.2.6 on 2025-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
