# Generated by Django 5.2.6 on 2025-09-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='principal',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='balance',
        ),
    ]
