# Generated by Django 5.2.6 on 2025-09-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_principal_deposit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=6, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='finance.account')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('account', 'snapshot_date')},
            },
        ),
    ]
