# Generated by Django 5.2.6 on 2025-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_accountdailybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
