# Generated by Django 5.2.4 on 2025-09-17 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
