# Generated by Django 5.2.4 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_issued_at_transaction_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'Waiting for Treasury'), ('waiting_sandogh', 'Waiting for Sandogh'), ('verified_khazanedar', 'Verified by Khazane dar'), ('done', 'Done')], default='waiting_treasury', max_length=40),
        ),
    ]
