# Generated by Django 5.2.4 on 2025-09-17 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transaction_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=40, null=True)),
                ('to_state', models.CharField(max_length=40)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Transaction State Log',
                'verbose_name_plural': 'Transaction State Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
