# Generated by Django 5.2.4 on 2025-09-20 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transactionstatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='funding_source',
            field=models.CharField(choices=[('wallet', 'Fund from User Wallet'), ('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='initial_funding_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deposit',
            name='funding_source',
            field=models.CharField(choices=[('wallet', 'Fund from User Wallet'), ('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='wallet', max_length=20),
        ),
    ]
