# Generated by Django 5.2.4 on 2025-09-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_account_funding_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='initial_balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
