# Generated by Django 5.2.4 on 2025-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_rename_amount_deposit_initial_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_wallet',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='account',
            name='funding_source',
            field=models.CharField(choices=[('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='funding_source',
            field=models.CharField(choices=[('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('credit_increase', 'Credit Increase'), ('withdrawal_request', 'Withdrawal Request'), ('account_to_account', 'Account to Account'), ('account_to_deposit_initial', 'Account to Deposit (Initial)'), ('profit_account', 'Account Profit Accrual'), ('profit_deposit_account', 'Deposit Profit to Account')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
