# Generated by Django 5.2.4 on 2025-09-20 13:43

from django.db import migrations, models
import uuid


def generate_user_ids(apps, schema_editor):
    User = apps.get_model('finance', 'User')
    for user in User.objects.all():
        user.user_id = uuid.uuid4()
        user.save(update_fields=['user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_wallet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(null=True, unique=True, editable=False, verbose_name='User ID'),
        ),
        migrations.RunPython(generate_user_ids),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, verbose_name='User ID'),
        ),
    ]
