# Generated by Django 5.2.4 on 2025-09-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20250920_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
            ],
            options={
                'verbose_name': 'Account Transfer',
                'verbose_name_plural': 'Account Transfers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='CreditIncrease',
            fields=[
            ],
            options={
                'verbose_name': 'Credit Increase',
                'verbose_name_plural': 'Credit Increases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Transaction',
                'verbose_name_plural': 'Deposit Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='ProfitTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Profit Transaction',
                'verbose_name_plural': 'Profit Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.transaction',),
        ),
        migrations.AddField(
            model_name='deposit',
            name='funding_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_deposits', to='finance.account'),
        ),
    ]
