# Generated by Django 5.2.4 on 2025-09-21 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_accounttransfer_creditincrease_deposittransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accounttransfer',
            options={'verbose_name': 'Account transfer', 'verbose_name_plural': 'Account transfers'},
        ),
        migrations.AlterModelOptions(
            name='creditincrease',
            options={'verbose_name': 'Credit increase', 'verbose_name_plural': 'Credit increases'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={'verbose_name': 'Deposit transaction', 'verbose_name_plural': 'Deposit transactions'},
        ),
        migrations.AlterModelOptions(
            name='profittransaction',
            options={'verbose_name': 'Profit transaction', 'verbose_name_plural': 'Profit transactions'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Withdrawal request', 'verbose_name_plural': 'Withdrawal requests'},
        ),
        migrations.AddField(
            model_name='transactionstatelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('rial', 'Rial account'), ('gold', 'Gold account'), ('foreign currency', 'Foreign Currency account')], max_length=20, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='funding_source',
            field=models.CharField(choices=[('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='none', max_length=20, verbose_name='Funding source'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Initial balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_funding_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial funding amount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_profit_accrual_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last profit accrual'),
        ),
        migrations.AlterField(
            model_name='account',
            name='monthly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly profit rate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Account name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='funding_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_deposits', to='finance.account', verbose_name='Funding account'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='funding_source',
            field=models.CharField(choices=[('transaction', 'Fund from Transaction'), ('none', 'No Initial Funding')], default='none', max_length=20, verbose_name='Funding source'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial balance'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='last_profit_accrual_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last profit accrual'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='monthly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly profit rate'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Applied'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_account_transactions', to='finance.account', verbose_name='Destination account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_deposit_transactions', to='finance.deposit', verbose_name='Destination deposit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Exchange rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('credit_increase', 'Credit increase'), ('withdrawal_request', 'Withdrawal request'), ('account_to_account', 'Account to account transfer'), ('account_to_deposit_initial', 'Account to deposit initial'), ('profit_account', 'Profit to account'), ('profit_deposit_account', 'Profit deposit to account')], max_length=40, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_account_transactions', to='finance.account', verbose_name='Source account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'Waiting treasury'), ('waiting_sandogh', 'Waiting sandogh'), ('verified_khazanedar', 'Verified khazanedar'), ('done', 'Done')], default='waiting_treasury', max_length=40, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
