# Generated by Django 5.2.4 on 2025-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_account_options_alter_accounttransfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, help_text='16-digit card number', max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='10-digit national ID', max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='11-digit phone number', max_length=11, verbose_name='شماره همراه'),
        ),
        migrations.AddField(
            model_name='user',
            name='sheba_number',
            field=models.CharField(blank=True, help_text='24-digit IBAN number', max_length=24, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
    ]
