# Generated by Django 5.2.4 on 2025-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_user_birth_date_user_card_number_user_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Transaction Code'),
        ),
    ]
