# Generated by Django 5.2.4 on 2025-09-21 11:55

from django.db import migrations
import uuid
from django.utils import timezone


def populate_transaction_codes(apps, schema_editor):
    """Populate transaction codes for existing transactions"""
    Transaction = apps.get_model('finance', 'Transaction')
    
    for transaction in Transaction.objects.filter(transaction_code__isnull=True):
        # Generate transaction code
        date_str = transaction.created_at.strftime('%Y%m%d')
        unique_part = str(uuid.uuid4())[:6].upper()
        transaction.transaction_code = f"TXN-{date_str}-{unique_part}"
        transaction.save(update_fields=['transaction_code'])


def reverse_populate_transaction_codes(apps, schema_editor):
    """Reverse migration - set transaction codes to None"""
    Transaction = apps.get_model('finance', 'Transaction')
    Transaction.objects.update(transaction_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_transaction_transaction_code'),
    ]

    operations = [
        migrations.RunPython(populate_transaction_codes, reverse_populate_transaction_codes),
    ]
