# Generated by Django 5.2.4 on 2025-09-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20250921_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='funding_source',
        ),
        migrations.RemoveField(
            model_name='account',
            name='initial_funding_amount',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='funding_account',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='funding_source',
        ),
    ]
