# Generated by Django 5.2.4 on 2025-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_account_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Upload receipt image (JPG format) for credit increase transactions', null=True, upload_to='receipts/', verbose_name='Receipt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_card_number',
            field=models.CharField(blank=True, help_text='16-digit card number for withdrawal', max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_sheba_number',
            field=models.CharField(blank=True, help_text='24-digit SHEBA number for withdrawal', max_length=24, verbose_name='شماره شبا'),
        ),
    ]
