# Generated by Django 5.2.4 on 2025-09-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_transaction_receipt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
    ]
