# Generated by Django 5.2.4 on 2025-09-22 09:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'حساب', 'verbose_name_plural': 'حساب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='accountdailybalance',
            options={'ordering': ['-snapshot_date'], 'verbose_name': 'موجودی روزانه حساب', 'verbose_name_plural': 'موجودی\u200cهای روزانه حساب'},
        ),
        migrations.AlterModelOptions(
            name='accounttransfer',
            options={'verbose_name': 'انتقال حساب', 'verbose_name_plural': 'انتقال\u200cهای حساب'},
        ),
        migrations.AlterModelOptions(
            name='creditincrease',
            options={'verbose_name': 'افزایش اعتبار', 'verbose_name_plural': 'افزایش\u200cهای اعتبار'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'سپرده', 'verbose_name_plural': 'سپرده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={'verbose_name': 'تراکنش سپرده', 'verbose_name_plural': 'تراکنش\u200cهای سپرده'},
        ),
        migrations.AlterModelOptions(
            name='profittransaction',
            options={'verbose_name': 'تراکنش سود', 'verbose_name_plural': 'تراکنش\u200cهای سود'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'گزارش وضعیت تراکنش', 'verbose_name_plural': 'گزارش\u200cهای وضعیت تراکنش'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست\u200cهای برداشت'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('rial', 'حساب ریالی'), ('gold', 'حساب طلا'), ('foreign currency', 'حساب ارزی')], max_length=20, verbose_name='نوع حساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='موجودی اولیه'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_profit_accrual_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تعلق سود'),
        ),
        migrations.AlterField(
            model_name='account',
            name='monthly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ سود ماهانه'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام حساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی اولیه'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='last_profit_accrual_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تعلق سود'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='monthly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ سود ماهانه'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='اعمال شده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_account_transactions', to='finance.account', verbose_name='حساب مقصد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_deposit_transactions', to='finance.deposit', verbose_name='سپرده مقصد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='نرخ تبدیل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('credit_increase', 'افزایش اعتبار'), ('withdrawal_request', 'درخواست برداشت'), ('account_to_account', 'انتقال حساب به حساب'), ('account_to_deposit_initial', 'حساب به سپرده اولیه'), ('profit_account', 'سود به حساب'), ('profit_deposit_account', 'سود سپرده به حساب')], max_length=40, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, help_text='آپلود تصویر رسید (فرمت JPG) برای تراکنش\u200cهای افزایش اعتبار', null=True, upload_to='receipts/', verbose_name='رسید'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی شده برای'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_account_transactions', to='finance.account', verbose_name='حساب مبدا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'در انتظار خزانه\u200cداری'), ('waiting_sandogh', 'در انتظار صندوق'), ('verified_khazanedar', 'تایید شده توسط خزانه\u200cدار'), ('done', 'انجام شده')], default='waiting_treasury', max_length=40, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='کد تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdrawal_card_number',
            field=models.CharField(blank=True, help_text='شماره کارت 16 رقمی برای برداشت', max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdrawal_sheba_number',
            field=models.CharField(blank=True, help_text='شماره شبا 24 رقمی برای برداشت', max_length=24, verbose_name='شماره شبا'),
        ),
        migrations.CreateModel(
            name='DepositDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=6, max_digits=18)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='finance.deposit')),
            ],
            options={
                'verbose_name': 'موجودی روزانه سپرده',
                'verbose_name_plural': 'موجودی\u200cهای روزانه سپرده',
                'ordering': ['-snapshot_date'],
                'unique_together': {('deposit', 'snapshot_date')},
            },
        ),
    ]
