# Generated by Django 5.2.4 on 2025-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_add_deposit_daily_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_opinion',
            field=models.TextField(blank=True, verbose_name='نظر ادمین'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='finance_manager_opinion',
            field=models.TextField(blank=True, verbose_name='نظر مدیر مالی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='treasurer_opinion',
            field=models.TextField(blank=True, verbose_name='نظر خزانه\u200cدار'),
        ),
    ]
