# Generated by Django 5.2.4 on 2025-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_add_transaction_opinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'در انتظار خزانه\u200cداری'), ('waiting_sandogh', 'در انتظار صندوق'), ('verified_khazanedar', 'تایید شده توسط خزانه\u200cدار'), ('waiting_time', 'در انتظار زمان تنظیم شده'), ('done', 'انجام شده')], default='waiting_treasury', max_length=40, verbose_name='وضعیت'),
        ),
    ]
