# Generated by Django 5.2.4 on 2025-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_add_waiting_time_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='کد تراکنش'),
        ),
    ]
