# Generated by Django 5.2.4 on 2025-09-24 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_transaction_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='breakage_coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نرخ ضریب شکست (%)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='profit_kind',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('yearly', 'سالانه')], default='monthly', max_length=10, verbose_name='نوع سود'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='monthly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ سود'),
        ),
    ]
