# Generated by Django 5.2.4 on 2025-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_deposit_breakage_coefficient_deposit_profit_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='نظر کاربر'),
        ),
    ]
