# Generated by Django 5.2.4 on 2025-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_transaction_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('rial', 'حساب ریالی'), ('gold', 'حساب طلا'), ('usd', 'حساب دلاری (USD)'), ('eur', 'حساب یورویی (EUR)'), ('gbp', 'حساب پوندی (GBP)'), ('foreign currency', 'حساب ارزی (قدیمی)')], max_length=20, verbose_name='نوع حساب'),
        ),
    ]
