# Generated by Django 5.2.4 on 2025-09-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dest_price_irr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='قیمت ارز مقصد بر حسب ریال'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='مبلغ مقصد'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_price_irr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='قیمت ارز مبدا بر حسب ریال'),
        ),
    ]
