# Generated by Django 5.2.4 on 2025-09-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_daily_balance_snapshot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='profit_kind',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('semiannual', 'شش\u200cماهه'), ('yearly', 'سالانه')], default='monthly', max_length=10, verbose_name='نوع سود'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'در انتظار خزانه\u200cداری'), ('waiting_sandogh', 'در انتظار صندوق'), ('verified_khazanedar', 'تایید شده توسط خزانه\u200cدار'), ('waiting_time', 'در انتظار زمان تنظیم شده'), ('done', 'انجام شده'), ('rejected', 'رد شده'), ('waiting_finance_manager', 'در انتظار تایید مدیر مالی')], default='waiting_treasury', max_length=40, verbose_name='وضعیت'),
        ),
    ]
