# Generated by Django 5.2.4 on 2025-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_add_transaction_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('waiting_treasury', 'در انتظار خزانه\u200cداری'), ('waiting_sandogh', 'در انتظار صندوق'), ('verified_khazanedar', 'تایید شده توسط خزانه\u200cدار'), ('waiting_time', 'در انتظار زمان تنظیم شده'), ('done', 'انجام شده'), ('rejected', 'رد شده'), ('waiting_finance_manager', 'در انتظار تایید مدیر مالی'), ('approved_by_finance_manager', 'تایید شده توسط مدیر مالی'), ('approved_by_sandogh', 'تایید شده توسط صندوق')], default='waiting_treasury', max_length=40, verbose_name='وضعیت'),
        ),
    ]
